In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("car.data", header=None)
df.columns = ["buying", "maint", "doors", "persons","lug_boot","safety","class_"]

In [3]:
df

     buying  maint  doors persons lug_boot safety class_
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [4]:
#buying
df.loc[df.buying == "low",'buying']= 1
df.loc[df.buying == "med",'buying']= 2
df.loc[df.buying == "high",'buying']= 3
df.loc[df.buying == "vhigh",'buying']= 4
#maint
df.loc[df.maint == "low",'maint']= 1
df.loc[df.maint == "med",'maint']= 2
df.loc[df.maint == "high",'maint']= 3
df.loc[df.maint == "vhigh",'maint']= 4
#doors
df.loc[df.doors == "5more",'doors']= 5
#persons
df.loc[df.persons == "more",'persons']= 5
#lug_but
df.loc[df.lug_boot == "small",'lug_boot']= 1
df.loc[df.lug_boot == "med",'lug_boot']= 2
df.loc[df.lug_boot == "big",'lug_boot']= 3
#safety
df.loc[df.safety == "low",'safety']= 1
df.loc[df.safety == "med",'safety']= 2
df.loc[df.safety == "high",'safety']= 3
#class
df.loc[df.class_ == "unacc",'class_']= 1
df.loc[df.class_ == "acc",'class_']= 2
df.loc[df.class_ == "good",'class_']= 3
df.loc[df.class_ == "vgood",'class_']= 4

In [5]:
df

     buying maint doors persons lug_boot safety class_
0         4     4     2       2        1      1      1
1         4     4     2       2        1      2      1
2         4     4     2       2        1      3      1
3         4     4     2       2        2      1      1
4         4     4     2       2        2      2      1
...     ...   ...   ...     ...      ...    ...    ...
1723      1     1     5       5        2      2      3
1724      1     1     5       5        2      3      4
1725      1     1     5       5        3      1      1
1726      1     1     5       5        3      2      3
1727      1     1     5       5        3      3      4

[1728 rows x 7 columns]